// Semantic UI catalog. UZ is the source and the fallback for every locale.
// International abbreviations intentionally remain unchanged.
const I18N_CATALOG = window.I18N_CATALOG = {
  uz: {
    'common.language':'Til','common.uzbek':'O‘zbekcha','common.russian':'Русский','common.english':'English','common.karakalpak':'Qaraqalpaqsha',
    'common.save':'Saqlash','common.cancel':'Bekor qilish','common.close':'Yopish','common.edit':'Tahrirlash','common.delete':'O‘chirish','common.add':'Qo‘shish','common.search':'Qidirish','common.filter':'Filtr','common.clear':'Tozalash','common.select':'Tanlang','common.yes':'Ha','common.no':'Yo‘q','common.back':'Orqaga','common.next':'Keyingi','common.continue':'Davom etish','common.refresh':'Yangilash','common.loading':'Yuklanmoqda...','common.saving':'Saqlanmoqda...','common.send':'Yuborish','common.export':'Eksport','common.print':'Chop etish','common.download':'Yuklab olish','common.view':'Ko‘rish','common.all':'Barchasi','common.actions':'Amallar','common.status':'Holat','common.date':'Sana','common.time':'Vaqt','common.total':'Jami','common.name':'Nomi','common.phone':'Telefon','common.address':'Manzil','common.region':'Viloyat','common.district':'Tuman','common.institution':'Muassasa','common.doctor':'Shifokor','common.patient':'Bemor','common.patients':'Bemorlar','common.male':'Erkak','common.female':'Ayol','common.age':'Yosh','common.birthDate':'Tug‘ilgan sana','common.fullName':'F.I.Sh.','common.unknown':'Noma’lum','common.notSpecified':'Ko‘rsatilmagan','common.noData':'Ma’lumot topilmadi','common.required':'Majburiy maydon','common.logout':'Tizimdan chiqish','common.settings':'Sozlamalar','common.profile':'Profil','common.notifications':'Bildirishnomalar','common.realtime':'Real-time monitoring',
    'nav.main':'Asosiy','nav.dashboard':'Bosh sahifa','nav.registries':'Reyestrlar','nav.analytics':'Tahlil va hisobot','nav.reports':'Hisobotlar','nav.extendedReport':'Kengaytirilgan hisobot','nav.patientMovement':'Bemor harakati','nav.route':'Marshrut','nav.users':'Foydalanuvchilar','nav.system':'Tizim','nav.pendingAdmission':'Qabul kutilmoqda','nav.newInfarct':'Yangi infarkt','nav.newStroke':'Yangi insult','nav.infarctRegistry':'Infarkt reyestri','nav.strokeRegistry':'Insult reyestri','nav.patients':'Bemorlar','nav.facilityCapabilities':'Muassasa imkoniyati','nav.registryPlatform':'Reyestri platformasi','nav.feedback':'Savol va takliflar yuborish',
    'auth.title':'Infarkt va insult reyestri','auth.signIn':'Tizimga kirish','auth.email':'Elektron pochta','auth.password':'Parol','auth.forgotPassword':'Parolni unutdingizmi?','auth.submit':'Kirish','auth.signingIn':'Kirilmoqda...','auth.signOutConfirm':'Tizimdan chiqmoqchimisiz?','auth.signedOut':'Tizimdan chiqdingiz','auth.sessionExpired':'Sessiya muddati tugadi — qayta kiring','auth.pending':'Akkaunt administrator tasdig‘ini kutmoqda',
    'roles.super_admin':'Super administrator','roles.admin':'Hudud administratori','roles.user':'Operator','roles.rahbar':'Rahbar (faqat ko‘rish)','roles.doctor':'Shifokor',
    'dashboard.title':'Bosh sahifa','dashboard.subtitle':'Real-time statistika va monitoring','dashboard.totalPatients':'Jami bemorlar','dashboard.infarct':'Infarkt','dashboard.stroke':'Insult','dashboard.stemi':'STEMI','dashboard.nstemi':'NSTEMI','dashboard.ischemicStroke':'Ishemik insult','dashboard.hemorrhagicStroke':'Gemorragik insult','dashboard.tia':'TIA','dashboard.thrombolysis':'Trombolizis','dashboard.pci':'PCI','dashboard.thrombectomy':'Trombektomiya','dashboard.mortality':'Letallik','dashboard.byRegion':'Hududlar bo‘yicha','dashboard.byInstitution':'Muassasalar bo‘yicha','dashboard.withinWindow':'Vaqt oynasiga yetib kelganlar','dashboard.lateArrival':'Kech murojaat qilganlar','dashboard.dynamics':'Dinamika','dashboard.monthlyDynamics':'Oylik dinamika','dashboard.statistics':'Statistika','dashboard.indicators':'Tizim ko‘rsatkichlari','dashboard.noData':'Tanlangan davr uchun ma’lumot yo‘q',
    'infarct.title':'Miokard infarkti','infarct.newPatient':'Yangi infarkt bemori','infarct.admissionForm':'Bemor qabul qilish formasi','infarct.acute':'O‘tkir miokard infarkti','infarct.acs':'O‘tkir koronar sindrom','infarct.stemi':'STEMI','infarct.stemiDescription':'ST segmenti ko‘tarilishi bilan kechuvchi miokard infarkti','infarct.nstemi':'NSTEMI','infarct.ami':'AMI','infarct.chestPain':'Ko‘krak qafasidagi og‘riq','infarct.painOnset':'Og‘riq boshlangan vaqt','infarct.presentationTime':'Bemor murojaat qilgan vaqt','infarct.ecgTime':'ECG olingan vaqt','infarct.stElevation':'ST elevatsiyasi','infarct.troponin':'Troponin','infarct.reperfusion':'Reperfuzion terapiya','infarct.thrombolyticTherapy':'Trombolitik terapiya','infarct.primaryPci':'Birlamchi PCI','infarct.rescuePci':'Rescue PCI','infarct.coronaryAngiography':'Koronarografiya','infarct.stenting':'Stentlash','infarct.cardiogenicShock':'Kardiogen shok','infarct.killipClass':'Killip klassi','infarct.graceScore':'GRACE skori','infarct.doorToBalloon':'Door-to-balloon','infarct.onsetToDoor':'Onset-to-door',
    'stroke.title':'Insult','stroke.newPatient':'Yangi insult bemori','stroke.ischemic':'Ishemik insult','stroke.hemorrhagic':'Gemorragik insult','stroke.tia':'TIA','stroke.symptomOnset':'Simptomlar boshlangan vaqt','stroke.lastKnownWell':'Oxirgi marta sog‘lom ko‘rilgan vaqt','stroke.neurologicDeficit':'Nevrologik nuqson','stroke.nihss':'NIHSS','stroke.aspects':'ASPECTS','stroke.gcs':'GCS','stroke.msct':'MSKT','stroke.ctAngiography':'KT angiografiya','stroke.thrombolysis':'Trombolizis','stroke.mechanicalThrombectomy':'Mexanik trombektomiya','stroke.lvo':'Katta tomir okklyuziyasi','stroke.ich':'Intrakranial qon ketishi','stroke.reperfusion':'Reperfuzion terapiya','stroke.doorToNeedle':'Door-to-needle',
    'form.personalData':'Shaxsiy ma’lumotlar','form.clinicalData':'Klinik ma’lumotlar','form.diagnostics':'Diagnostika','form.treatment':'Davolash','form.procedures':'Muolajalar','form.routing':'Yo‘naltirish va marshrutizatsiya','form.complaints':'Shikoyatlar','form.diagnosis':'Tashxis','form.selectReason':'Sababni tanlang','form.continueSaving':'Saqlashni davom ettirish','form.patientId':'Bemor ID','form.medicalCard':'Bemor kartasi','form.ktNumber':'K/T raqami','form.registryList':'Bemorlar ro‘yxati','form.allRegistryPatients':'Barcha registr bemorlari','form.fromInstitution':'Muassasadan kelgan bemorni qabul qilish',
    'calc.totalScore':'Umumiy ball','calc.clinicalInterpretation':'Klinik izoh','calc.nihssScore':'NIHSS umumiy ball','calc.aspectsScore':'ASPECTS ball','calc.gcsScore':'GCS ball','calc.graceScore':'GRACE skori','calc.killipClass':'Killip klassi','calc.aha':'AHA tasnifi',
    'reports.title':'Hisobotlar','reports.subtitle':'Statistik tahlil va hisobotlar','reports.period':'Hisobot davri','reports.from':'Dan','reports.to':'Gacha','reports.excel':'Excelga eksport','reports.pdf':'PDFga eksport','reports.table':'Jadval','reports.chart':'Grafik','reports.legend':'Legenda','reports.quantity':'Soni','reports.percent':'Foiz',
    'validation.required':'Ushbu maydonni to‘ldiring.','validation.invalid':'Kiritilgan qiymat noto‘g‘ri.','validation.invalidEmail':'Elektron pochta manzili noto‘g‘ri.','validation.duplicate':'Ushbu ma’lumot avval ro‘yxatdan o‘tkazilgan.','validation.network':'Tarmoq bilan bog‘lanishda xatolik.','validation.generic':'Xatolik yuz berdi. Qayta urinib ko‘ring.','validation.selectReason':'Sababni tanlang','validation.fillRequired':'Barcha majburiy maydonlarni to‘ldiring.','validation.loadFailed':'Sahifani yuklashda xato','validation.retry':'Qayta urinish','validation.successSaved':'Ma’lumot muvaffaqiyatli saqlandi.','validation.deleted':'Ma’lumot o‘chirildi.','validation.updated':'Ma’lumot yangilandi.',
    'status.pending':'Kutilmoqda','status.completed':'Yakunlangan','status.referred':'Yo‘naltirilgan','status.transferred':'O‘tkazilgan','status.alive':'Tirik','status.dead':'Vafot etgan','status.active':'Faol','status.inactive':'Nofaol','status.accepted':'Qabul qilindi','status.rejected':'Rad etildi',
    'units.minute':'daqiqa','units.hour':'soat','units.day':'kun','units.patient':'bemor','units.mg':'mg','units.kg':'kg','units.mmhg':'mmHg','units.mmolL':'mmol/L','units.mgDl':'mg/dL','units.bpm':'bpm'
  },
  ru: {}, en: {}, kk: {}
};

// Compact, reviewable overrides: keys not listed here fall back to UZ by design.
Object.assign(I18N_CATALOG.ru, {
  'common.language':'Язык','common.uzbek':'O‘zbekcha','common.russian':'Русский','common.english':'English','common.karakalpak':'Qaraqalpaqsha','common.save':'Сохранить','common.cancel':'Отмена','common.close':'Закрыть','common.edit':'Изменить','common.delete':'Удалить','common.add':'Добавить','common.search':'Поиск','common.filter':'Фильтр','common.clear':'Очистить','common.select':'Выберите','common.yes':'Да','common.no':'Нет','common.back':'Назад','common.next':'Далее','common.continue':'Продолжить','common.refresh':'Обновить','common.loading':'Загрузка...','common.saving':'Сохранение...','common.send':'Отправить','common.export':'Экспорт','common.print':'Печать','common.download':'Скачать','common.view':'Просмотр','common.all':'Все','common.actions':'Действия','common.status':'Статус','common.date':'Дата','common.time':'Время','common.total':'Всего','common.name':'Наименование','common.phone':'Телефон','common.address':'Адрес','common.region':'Область','common.district':'Район','common.institution':'Учреждение','common.doctor':'Врач','common.patient':'Пациент','common.patients':'Пациенты','common.male':'Мужчина','common.female':'Женщина','common.age':'Возраст','common.birthDate':'Дата рождения','common.fullName':'Ф.И.О.','common.unknown':'Неизвестно','common.notSpecified':'Не указано','common.noData':'Данные не найдены','common.required':'Обязательное поле','common.logout':'Выйти','common.settings':'Настройки','common.profile':'Профиль','common.notifications':'Уведомления','common.realtime':'Мониторинг в реальном времени',
  'nav.main':'Главное','nav.dashboard':'Главная','nav.registries':'Реестры','nav.analytics':'Аналитика и отчёты','nav.reports':'Отчёты','nav.extendedReport':'Расширенный отчёт','nav.patientMovement':'Движение пациента','nav.route':'Маршрут','nav.users':'Пользователи','nav.system':'Система','nav.pendingAdmission':'Ожидают приёма','nav.newInfarct':'Новый инфаркт','nav.newStroke':'Новый инсульт','nav.infarctRegistry':'Реестр инфаркта','nav.strokeRegistry':'Реестр инсульта','nav.patients':'Пациенты','nav.facilityCapabilities':'Возможности учреждения','nav.registryPlatform':'Платформа реестра','nav.feedback':'Вопросы и предложения',
  'auth.title':'Реестр инфаркта и инсульта','auth.signIn':'Вход в систему','auth.email':'Электронная почта','auth.password':'Пароль','auth.forgotPassword':'Забыли пароль?','auth.submit':'Войти','auth.signingIn':'Вход...','auth.signOutConfirm':'Выйти из системы?','auth.signedOut':'Вы вышли из системы','auth.sessionExpired':'Сессия истекла — войдите снова','auth.pending':'Учётная запись ожидает подтверждения администратора',
  'roles.super_admin':'Суперадминистратор','roles.admin':'Региональный администратор','roles.user':'Оператор','roles.rahbar':'Руководитель (только просмотр)','roles.doctor':'Врач',
  'dashboard.title':'Главная','dashboard.subtitle':'Статистика и мониторинг в реальном времени','dashboard.totalPatients':'Всего пациентов','dashboard.infarct':'Инфаркт','dashboard.stroke':'Инсульт','dashboard.ischemicStroke':'Ишемический инсульт','dashboard.hemorrhagicStroke':'Геморрагический инсульт','dashboard.thrombolysis':'Тромболизис','dashboard.thrombectomy':'Тромбэктомия','dashboard.mortality':'Летальность','dashboard.byRegion':'По регионам','dashboard.byInstitution':'По учреждениям','dashboard.withinWindow':'Поступили в терапевтическое окно','dashboard.lateArrival':'Позднее обращение','dashboard.dynamics':'Динамика','dashboard.monthlyDynamics':'Динамика по месяцам','dashboard.statistics':'Статистика','dashboard.indicators':'Показатели системы','dashboard.noData':'Нет данных за выбранный период',
  'infarct.title':'Инфаркт миокарда','infarct.newPatient':'Новый пациент с инфарктом','infarct.admissionForm':'Форма приёма пациента','infarct.acute':'Острый инфаркт миокарда','infarct.acs':'Острый коронарный синдром','infarct.stemiDescription':'Инфаркт миокарда с подъёмом сегмента ST','infarct.chestPain':'Боль в грудной клетке','infarct.painOnset':'Время начала боли','infarct.presentationTime':'Время обращения пациента','infarct.ecgTime':'Время регистрации ECG','infarct.stElevation':'Элевация ST','infarct.troponin':'Тропонин','infarct.reperfusion':'Реперфузионная терапия','infarct.thrombolyticTherapy':'Тромболитическая терапия','infarct.primaryPci':'Первичное PCI','infarct.coronaryAngiography':'Коронарография','infarct.stenting':'Стентирование','infarct.cardiogenicShock':'Кардиогенный шок','infarct.killipClass':'Класс Killip','infarct.graceScore':'Шкала GRACE',
  'stroke.title':'Инсульт','stroke.newPatient':'Новый пациент с инсультом','stroke.ischemic':'Ишемический инсульт','stroke.hemorrhagic':'Геморрагический инсульт','stroke.symptomOnset':'Время начала симптомов','stroke.lastKnownWell':'Время, когда пациент последний раз был без симптомов','stroke.neurologicDeficit':'Неврологический дефицит','stroke.ctAngiography':'КТ-ангиография','stroke.thrombolysis':'Тромболизис','stroke.mechanicalThrombectomy':'Механическая тромбэктомия','stroke.lvo':'Окклюзия крупного сосуда','stroke.ich':'Внутричерепное кровоизлияние','stroke.reperfusion':'Реперфузионная терапия',
  'form.personalData':'Персональные данные','form.clinicalData':'Клинические данные','form.diagnostics':'Диагностика','form.treatment':'Лечение','form.procedures':'Процедуры','form.routing':'Направление и маршрутизация','form.complaints':'Жалобы','form.diagnosis':'Диагноз','form.selectReason':'Выберите причину','form.continueSaving':'Продолжить сохранение','form.patientId':'ID пациента','form.medicalCard':'Карта пациента','form.ktNumber':'Номер К/Т','form.registryList':'Список пациентов','form.allRegistryPatients':'Все пациенты реестра','form.fromInstitution':'Приём пациента из другого учреждения',
  'calc.totalScore':'Общий балл','calc.clinicalInterpretation':'Клиническая интерпретация','calc.nihssScore':'Общий балл NIHSS','calc.aspectsScore':'Балл ASPECTS','calc.gcsScore':'Балл GCS','calc.graceScore':'Шкала GRACE','calc.killipClass':'Класс Killip','calc.aha':'Классификация AHA',
  'reports.title':'Отчёты','reports.subtitle':'Статистический анализ и отчёты','reports.period':'Отчётный период','reports.from':'С','reports.to':'По','reports.excel':'Экспорт в Excel','reports.pdf':'Экспорт в PDF','reports.table':'Таблица','reports.chart':'График','reports.legend':'Легенда','reports.quantity':'Количество','reports.percent':'Процент',
  'validation.required':'Заполните это поле.','validation.invalid':'Введено неверное значение.','validation.invalidEmail':'Неверный адрес электронной почты.','validation.duplicate':'Эти данные уже зарегистрированы.','validation.network':'Ошибка подключения к сети.','validation.generic':'Произошла ошибка. Повторите попытку.','validation.selectReason':'Выберите причину','validation.fillRequired':'Заполните все обязательные поля.','validation.loadFailed':'Ошибка загрузки страницы','validation.retry':'Повторить','validation.successSaved':'Данные успешно сохранены.','validation.deleted':'Данные удалены.','validation.updated':'Данные обновлены.',
  'status.pending':'Ожидается','status.completed':'Завершено','status.referred':'Направлен','status.transferred':'Переведён','status.alive':'Жив','status.dead':'Умер','status.active':'Активен','status.inactive':'Неактивен','status.accepted':'Принят','status.rejected':'Отклонён','units.minute':'мин','units.hour':'час','units.day':'день','units.patient':'пациент'
});

Object.assign(I18N_CATALOG.en, {
  'common.language':'Language','common.save':'Save','common.cancel':'Cancel','common.close':'Close','common.edit':'Edit','common.delete':'Delete','common.add':'Add','common.search':'Search','common.filter':'Filter','common.clear':'Clear','common.select':'Select','common.yes':'Yes','common.no':'No','common.back':'Back','common.next':'Next','common.continue':'Continue','common.refresh':'Refresh','common.loading':'Loading...','common.saving':'Saving...','common.send':'Send','common.export':'Export','common.print':'Print','common.download':'Download','common.view':'View','common.all':'All','common.actions':'Actions','common.status':'Status','common.date':'Date','common.time':'Time','common.total':'Total','common.name':'Name','common.phone':'Phone','common.address':'Address','common.region':'Region','common.district':'District','common.institution':'Institution','common.doctor':'Doctor','common.patient':'Patient','common.patients':'Patients','common.male':'Male','common.female':'Female','common.age':'Age','common.birthDate':'Date of birth','common.fullName':'Full name','common.unknown':'Unknown','common.notSpecified':'Not specified','common.noData':'No data found','common.required':'Required field','common.logout':'Sign out','common.settings':'Settings','common.profile':'Profile','common.notifications':'Notifications','common.realtime':'Real-time monitoring',
  'nav.main':'Main','nav.dashboard':'Dashboard','nav.registries':'Registries','nav.analytics':'Analytics and reports','nav.reports':'Reports','nav.extendedReport':'Extended report','nav.patientMovement':'Patient movement','nav.route':'Routing','nav.users':'Users','nav.system':'System','nav.pendingAdmission':'Pending admission','nav.newInfarct':'New infarction','nav.newStroke':'New stroke','nav.infarctRegistry':'Infarction registry','nav.strokeRegistry':'Stroke registry','nav.patients':'Patients','nav.facilityCapabilities':'Facility capabilities','nav.registryPlatform':'Registry platform','nav.feedback':'Questions and feedback',
  'auth.title':'Infarction and Stroke Registry','auth.signIn':'Sign in','auth.email':'Email','auth.password':'Password','auth.forgotPassword':'Forgot password?','auth.submit':'Sign in','auth.signingIn':'Signing in...','auth.signOutConfirm':'Do you want to sign out?','auth.signedOut':'You have signed out','auth.sessionExpired':'Your session has expired — sign in again','auth.pending':'The account is awaiting administrator approval',
  'roles.super_admin':'Super administrator','roles.admin':'Regional administrator','roles.user':'Operator','roles.rahbar':'Manager (view only)','roles.doctor':'Doctor',
  'dashboard.title':'Dashboard','dashboard.subtitle':'Real-time statistics and monitoring','dashboard.totalPatients':'Total patients','dashboard.infarct':'Infarction','dashboard.stroke':'Stroke','dashboard.ischemicStroke':'Ischemic stroke','dashboard.hemorrhagicStroke':'Hemorrhagic stroke','dashboard.thrombolysis':'Thrombolysis','dashboard.thrombectomy':'Thrombectomy','dashboard.mortality':'Mortality','dashboard.byRegion':'By region','dashboard.byInstitution':'By institution','dashboard.withinWindow':'Arrived within the treatment window','dashboard.lateArrival':'Late presentation','dashboard.dynamics':'Trends','dashboard.monthlyDynamics':'Monthly trends','dashboard.statistics':'Statistics','dashboard.indicators':'System indicators','dashboard.noData':'No data for the selected period',
  'infarct.title':'Myocardial infarction','infarct.newPatient':'New infarction patient','infarct.admissionForm':'Patient admission form','infarct.acute':'Acute myocardial infarction','infarct.acs':'Acute coronary syndrome','infarct.stemiDescription':'ST-elevation myocardial infarction','infarct.chestPain':'Chest pain','infarct.painOnset':'Pain onset time','infarct.presentationTime':'Patient presentation time','infarct.ecgTime':'ECG acquisition time','infarct.stElevation':'ST elevation','infarct.troponin':'Troponin','infarct.reperfusion':'Reperfusion therapy','infarct.thrombolyticTherapy':'Thrombolytic therapy','infarct.primaryPci':'Primary PCI','infarct.coronaryAngiography':'Coronary angiography','infarct.stenting':'Stenting','infarct.cardiogenicShock':'Cardiogenic shock','infarct.killipClass':'Killip class','infarct.graceScore':'GRACE score',
  'stroke.title':'Stroke','stroke.newPatient':'New stroke patient','stroke.ischemic':'Ischemic stroke','stroke.hemorrhagic':'Hemorrhagic stroke','stroke.symptomOnset':'Symptom onset time','stroke.lastKnownWell':'Last known well time','stroke.neurologicDeficit':'Neurological deficit','stroke.ctAngiography':'CT angiography','stroke.thrombolysis':'Thrombolysis','stroke.mechanicalThrombectomy':'Mechanical thrombectomy','stroke.lvo':'Large-vessel occlusion','stroke.ich':'Intracranial hemorrhage','stroke.reperfusion':'Reperfusion therapy',
  'form.personalData':'Personal information','form.clinicalData':'Clinical information','form.diagnostics':'Diagnostics','form.treatment':'Treatment','form.procedures':'Procedures','form.routing':'Referral and routing','form.complaints':'Complaints','form.diagnosis':'Diagnosis','form.selectReason':'Select a reason','form.continueSaving':'Continue saving','form.patientId':'Patient ID','form.medicalCard':'Patient record','form.ktNumber':'K/T number','form.registryList':'Patient list','form.allRegistryPatients':'All registry patients','form.fromInstitution':'Admit a patient from another institution',
  'calc.totalScore':'Total score','calc.clinicalInterpretation':'Clinical interpretation','calc.nihssScore':'Total NIHSS score','calc.aspectsScore':'ASPECTS score','calc.gcsScore':'GCS score','calc.graceScore':'GRACE score','calc.killipClass':'Killip class','calc.aha':'AHA classification',
  'reports.title':'Reports','reports.subtitle':'Statistical analysis and reports','reports.period':'Reporting period','reports.from':'From','reports.to':'To','reports.excel':'Export to Excel','reports.pdf':'Export to PDF','reports.table':'Table','reports.chart':'Chart','reports.legend':'Legend','reports.quantity':'Count','reports.percent':'Percent',
  'validation.required':'Complete this field.','validation.invalid':'The entered value is invalid.','validation.invalidEmail':'The email address is invalid.','validation.duplicate':'This record has already been registered.','validation.network':'Network connection error.','validation.generic':'An error occurred. Please try again.','validation.selectReason':'Select a reason','validation.fillRequired':'Complete all required fields.','validation.loadFailed':'Failed to load the page','validation.retry':'Try again','validation.successSaved':'Data saved successfully.','validation.deleted':'Data deleted.','validation.updated':'Data updated.',
  'status.pending':'Pending','status.completed':'Completed','status.referred':'Referred','status.transferred':'Transferred','status.alive':'Alive','status.dead':'Deceased','status.active':'Active','status.inactive':'Inactive','status.accepted':'Accepted','status.rejected':'Rejected','units.minute':'min','units.hour':'hour','units.day':'day','units.patient':'patient'
});

Object.assign(I18N_CATALOG.kk, {
  'common.language':'Til','common.save':'Saqlaw','common.cancel':'Biykar etiw','common.close':'Jabıw','common.edit':'Ózgertiw','common.delete':'Óshiriw','common.add':'Qosıw','common.search':'Izlew','common.filter':'Filtr','common.clear':'Tazalaw','common.select':'Tańlań','common.yes':'Awa','common.no':'Yaq','common.back':'Artqa','common.next':'Keyingi','common.continue':'Dawam etiw','common.refresh':'Jańalaw','common.loading':'Júklenbekte...','common.saving':'Saqlanbaqta...','common.send':'Jiberiw','common.export':'Eksport','common.print':'Baspaǵa shıǵarıw','common.download':'Júklep alıw','common.view':'Kóriw','common.all':'Hámmesi','common.actions':'Ámeller','common.status':'Jaǵday','common.date':'Sáne','common.time':'Waqıt','common.total':'Jámi','common.name':'Ataması','common.phone':'Telefon','common.address':'Mánzil','common.region':'Wálayat','common.district':'Rayon','common.institution':'Mákeme','common.doctor':'Shıpaker','common.patient':'Nawqas','common.patients':'Nawqaslar','common.male':'Er adam','common.female':'Hayal','common.age':'Jas','common.birthDate':'Tuwılǵan sáne','common.fullName':'F.A.Á.','common.unknown':'Belgisiz','common.notSpecified':'Kórsetilmegen','common.noData':'Maǵlıwmat tabılmadı','common.required':'Májbúriy maydan','common.logout':'Sistemadan shıǵıw','common.settings':'Sazlawlar','common.profile':'Profil','common.notifications':'Bildiriwler','common.realtime':'Real-time monitoring',
  'nav.main':'Tiykarǵı','nav.dashboard':'Bas bet','nav.registries':'Reyestrler','nav.analytics':'Analitika hám esabat','nav.reports':'Esabatlar','nav.extendedReport':'Keńeytilgen esabat','nav.patientMovement':'Nawqas háreketi','nav.route':'Marshrut','nav.users':'Paydalanıwshılar','nav.system':'Sistema','nav.pendingAdmission':'Qabıllaw kútilmekte','nav.newInfarct':'Jańa infarkt','nav.newStroke':'Jańa insult','nav.infarctRegistry':'Infarkt reyestri','nav.strokeRegistry':'Insult reyestri','nav.patients':'Nawqaslar','nav.facilityCapabilities':'Mákeme imkaniyatı','nav.registryPlatform':'Reyestr platforması','nav.feedback':'Soraw hám usınıslar',
  'auth.title':'Infarkt hám insult reyestri','auth.signIn':'Sistemaǵa kiriw','auth.email':'Elektron pochta','auth.password':'Parol','auth.forgotPassword':'Paroldı umıttıńız ba?','auth.submit':'Kiriw','auth.signingIn':'Kirip atır...','auth.signOutConfirm':'Sistemadan shıǵasız ba?','auth.signedOut':'Sistemadan shıqtıńız','auth.sessionExpired':'Sessiya múddeti tamamlandı — qayta kiriń','auth.pending':'Akkaunt administrator tastıyıqlawın kútpekte',
  'roles.super_admin':'Super administrator','roles.admin':'Aymaq administratorı','roles.user':'Operator','roles.rahbar':'Basshı (tek kóriw)','roles.doctor':'Shıpaker',
  'dashboard.title':'Bas bet','dashboard.subtitle':'Real-time statistika hám monitoring','dashboard.totalPatients':'Jámi nawqaslar','dashboard.infarct':'Infarkt','dashboard.stroke':'Insult','dashboard.ischemicStroke':'Ishemiyalıq insult','dashboard.hemorrhagicStroke':'Gemorragiyalıq insult','dashboard.thrombolysis':'Trombolizis','dashboard.thrombectomy':'Trombektomiya','dashboard.mortality':'Letallıq','dashboard.byRegion':'Aymaqlar boyınsha','dashboard.byInstitution':'Mákemeler boyınsha','dashboard.withinWindow':'Waqıt aynasında kelgenler','dashboard.lateArrival':'Kesh múrájat etkenler','dashboard.dynamics':'Dinamika','dashboard.monthlyDynamics':'Aylıq dinamika','dashboard.statistics':'Statistika','dashboard.indicators':'Sistema kórsetkishleri','dashboard.noData':'Tańlanǵan dáwir ushın maǵlıwmat joq',
  'infarct.title':'Miokard infarktı','infarct.newPatient':'Jańa infarkt nawqası','infarct.admissionForm':'Nawqastı qabıllaw forması','infarct.acute':'Ótkir miokard infarktı','infarct.acs':'Ótkir koronar sindrom','infarct.stemiDescription':'ST segmenti kóteriliwi menen ótetuǵın miokard infarktı','infarct.chestPain':'Kókirek qápesindegi awırıw','infarct.painOnset':'Awırıw baslanǵan waqıt','infarct.presentationTime':'Nawqas múrájat etken waqıt','infarct.ecgTime':'ECG alınǵan waqıt','infarct.stElevation':'ST elevaciyası','infarct.troponin':'Troponin','infarct.reperfusion':'Reperfuziyalıq terapiya','infarct.thrombolyticTherapy':'Trombolitikalıq terapiya','infarct.primaryPci':'Birlemshi PCI','infarct.coronaryAngiography':'Koronarografiya','infarct.stenting':'Stentlew','infarct.cardiogenicShock':'Kardiogen shok','infarct.killipClass':'Killip klassı','infarct.graceScore':'GRACE skorı',
  'stroke.title':'Insult','stroke.newPatient':'Jańa insult nawqası','stroke.ischemic':'Ishemiyalıq insult','stroke.hemorrhagic':'Gemorragiyalıq insult','stroke.symptomOnset':'Simptomlar baslanǵan waqıt','stroke.lastKnownWell':'Sońǵı ret saw kórilgen waqıt','stroke.neurologicDeficit':'Nevrologiyalıq nuqsan','stroke.ctAngiography':'KT angiografiya','stroke.thrombolysis':'Trombolizis','stroke.mechanicalThrombectomy':'Mexanikalıq trombektomiya','stroke.lvo':'Úlken tamır okklyuziyası','stroke.ich':'Intrakranial qan ketiwi','stroke.reperfusion':'Reperfuziyalıq terapiya',
  'form.personalData':'Jeke maǵlıwmatlar','form.clinicalData':'Klinikalıq maǵlıwmatlar','form.diagnostics':'Diagnostika','form.treatment':'Emlew','form.procedures':'Emlew ilajları','form.routing':'Jollama hám marshrutizaciya','form.complaints':'Shaǵımlar','form.diagnosis':'Diagnoz','form.selectReason':'Sebebin tańlań','form.continueSaving':'Saqlawdı dawam ettiriw','form.patientId':'Nawqas ID','form.medicalCard':'Nawqas kartası','form.ktNumber':'K/T nomeri','form.registryList':'Nawqaslar dizimi','form.allRegistryPatients':'Reyestrdegi barlıq nawqaslar','form.fromInstitution':'Basqa mákemeden kelgen nawqastı qabıllaw',
  'calc.totalScore':'Ulıwma ball','calc.clinicalInterpretation':'Klinikalıq túsindirme','calc.nihssScore':'NIHSS ulıwma ball','calc.aspectsScore':'ASPECTS ball','calc.gcsScore':'GCS ball','calc.graceScore':'GRACE skorı','calc.killipClass':'Killip klassı','calc.aha':'AHA klassifikaciyası',
  'reports.title':'Esabatlar','reports.subtitle':'Statistikalıq analiz hám esabatlar','reports.period':'Esabat dáwiri','reports.from':'Baslap','reports.to':'Shekem','reports.excel':'Excel-ge eksport','reports.pdf':'PDF-ke eksport','reports.table':'Keste','reports.chart':'Grafik','reports.legend':'Legenda','reports.quantity':'Sanı','reports.percent':'Procent',
  'validation.required':'Bul maydandı toldırıń.','validation.invalid':'Kirgizilgen mánis nadurıs.','validation.invalidEmail':'Elektron pochta mánzili nadurıs.','validation.duplicate':'Bul maǵlıwmat aldın dizimnen ótkerilgen.','validation.network':'Taramaqqa jalǵanıwda qátelik.','validation.generic':'Qátelik júz berdi. Qayta urınıp kóriń.','validation.selectReason':'Sebebin tańlań','validation.fillRequired':'Barlıq májbúriy maydanlardı toldırıń.','validation.loadFailed':'Betti júklewde qátelik','validation.retry':'Qayta urınıw','validation.successSaved':'Maǵlıwmat tabıslı saqlandı.','validation.deleted':'Maǵlıwmat óshirildi.','validation.updated':'Maǵlıwmat jańalandı.',
  'status.pending':'Kútilmekte','status.completed':'Juwmaqlanǵan','status.referred':'Jollanǵan','status.transferred':'Ótkerilgen','status.alive':'Tiri','status.dead':'Qaytıs bolǵan','status.active':'Aktiv','status.inactive':'Aktiv emes','status.accepted':'Qabıl etildi','status.rejected':'Biykar etildi','units.minute':'minut','units.hour':'saat','units.day':'kún','units.patient':'nawqas'
});

// Page-level phrases that are shared by authentication, administration and registries.
Object.assign(I18N_CATALOG.uz, {
  'auth.welcome':'Xush kelibsiz','auth.instructions':'Tizimga kirish uchun ma’lumotlaringizni kiriting','auth.emailAddress':'Email manzil','auth.success':'Muvaffaqiyatli kirdingiz!','auth.register':'Ro‘yxatdan o‘tish','auth.fullName':'To‘liq ism','auth.chooseRegionFirst':'Avval viloyatni tanlang','auth.chooseInstitution':'Muassasangizni tanlang...','auth.haveAccount':'Hisobingiz bormi?','auth.noAccount':'Hisobingiz yo‘qmi?',
  'pages.adminTitle':'Admin panel','pages.adminSubtitle':'Tizim boshqaruvi','pages.patientCard':'Bemor kartasi','pages.patientList':'Bemorlar ro‘yxati','pages.allPatients':'Barcha registr bemorlari','pages.movementSubtitle':'Ko‘p muassasaga o‘tgan bemorlar','pages.registrySubtitle':'Viloyatlar va muassasalar tahlili','pages.settingsSubtitle':'Profil va parol sozlamalari','pages.capabilitiesSubtitle':'MSKT va angiografiya mavjudligi — yo‘naltirish filtri uchun','pages.pendingSubtitle':'Boshqa muassasadan yuborilgan bemorlar','pages.routeSubtitle':'Bemorning muassasalar orasidagi harakati va marshrut sifati','pages.extendedSubtitle':'Viloyat va muassasa kesimida to‘liq tahlil — jadval, marshrut, kaskad',
  'feedback.problem':'Muammo','feedback.suggestion':'Taklif','feedback.question':'Savol','feedback.message':'Xabar','feedback.waiting':'Kutilmoqda...','feedback.reply':'Javob keldi','feedback.myMessages':'Mening xabarlarim','feedback.sendSuccess':'Xabaringiz muvaffaqiyatli yuborildi!','feedback.placeholder':'Muammo yoki taklifingizni batafsil yozing...','feedback.required':'Xabar matnini kiriting','feedback.sendError':'Xabarni yuborib bo‘lmadi. Qayta urinib ko‘ring.'
});
Object.assign(I18N_CATALOG.ru, {
  'auth.welcome':'Добро пожаловать','auth.instructions':'Введите данные для входа в систему','auth.emailAddress':'Электронная почта','auth.success':'Вход выполнен успешно!','auth.register':'Регистрация','auth.fullName':'Полное имя','auth.chooseRegionFirst':'Сначала выберите область','auth.chooseInstitution':'Выберите учреждение...','auth.haveAccount':'Уже есть учётная запись?','auth.noAccount':'Нет учётной записи?',
  'pages.adminTitle':'Панель администратора','pages.adminSubtitle':'Управление системой','pages.patientCard':'Карта пациента','pages.patientList':'Список пациентов','pages.allPatients':'Все пациенты реестра','pages.movementSubtitle':'Пациенты, переведённые между учреждениями','pages.registrySubtitle':'Анализ по областям и учреждениям','pages.settingsSubtitle':'Настройки профиля и пароля','pages.capabilitiesSubtitle':'Наличие MSCT и ангиографии для маршрутизации','pages.pendingSubtitle':'Пациенты, направленные из других учреждений','pages.routeSubtitle':'Движение пациента между учреждениями и качество маршрута','pages.extendedSubtitle':'Полный анализ по областям и учреждениям — таблица, маршрут, каскад',
  'feedback.problem':'Проблема','feedback.suggestion':'Предложение','feedback.question':'Вопрос','feedback.message':'Сообщение','feedback.waiting':'Ожидается...','feedback.reply':'Получен ответ','feedback.myMessages':'Мои сообщения','feedback.sendSuccess':'Сообщение успешно отправлено!','feedback.placeholder':'Подробно опишите проблему или предложение...','feedback.required':'Введите текст сообщения','feedback.sendError':'Не удалось отправить сообщение. Повторите попытку.'
});
Object.assign(I18N_CATALOG.en, {
  'auth.welcome':'Welcome','auth.instructions':'Enter your credentials to sign in','auth.emailAddress':'Email address','auth.success':'Signed in successfully!','auth.register':'Register','auth.fullName':'Full name','auth.chooseRegionFirst':'Select a region first','auth.chooseInstitution':'Select your institution...','auth.haveAccount':'Already have an account?','auth.noAccount':'Do not have an account?',
  'pages.adminTitle':'Admin panel','pages.adminSubtitle':'System administration','pages.patientCard':'Patient record','pages.patientList':'Patient list','pages.allPatients':'All registry patients','pages.movementSubtitle':'Patients transferred between institutions','pages.registrySubtitle':'Analysis by region and institution','pages.settingsSubtitle':'Profile and password settings','pages.capabilitiesSubtitle':'MSCT and angiography availability for routing','pages.pendingSubtitle':'Patients referred from other institutions','pages.routeSubtitle':'Patient movement between institutions and route quality','pages.extendedSubtitle':'Complete analysis by region and institution — table, route, cascade',
  'feedback.problem':'Problem','feedback.suggestion':'Suggestion','feedback.question':'Question','feedback.message':'Message','feedback.waiting':'Pending...','feedback.reply':'Reply received','feedback.myMessages':'My messages','feedback.sendSuccess':'Your message was sent successfully!','feedback.placeholder':'Describe the problem or suggestion in detail...','feedback.required':'Enter a message','feedback.sendError':'The message could not be sent. Please try again.'
});
Object.assign(I18N_CATALOG.kk, {
  'auth.welcome':'Xosh keldińiz','auth.instructions':'Sistemaǵa kiriw ushın maǵlıwmatlarıńızdı kirgiziń','auth.emailAddress':'Elektron pochta','auth.success':'Tabıslı kirdińiz!','auth.register':'Dizimnen ótiw','auth.fullName':'Tolıq atı','auth.chooseRegionFirst':'Aldın wálayattı tańlań','auth.chooseInstitution':'Mákemeńizdi tańlań...','auth.haveAccount':'Akkauntıńız bar ma?','auth.noAccount':'Akkauntıńız joq pa?',
  'pages.adminTitle':'Administrator paneli','pages.adminSubtitle':'Sistemanı basqarıw','pages.patientCard':'Nawqas kartası','pages.patientList':'Nawqaslar dizimi','pages.allPatients':'Reyestrdegi barlıq nawqaslar','pages.movementSubtitle':'Birneshe mákemege ótken nawqaslar','pages.registrySubtitle':'Wálayatlar hám mákemeler analizi','pages.settingsSubtitle':'Profil hám parol sazlawları','pages.capabilitiesSubtitle':'Marshrutizaciya ushın MSKT hám angiografiya barlıǵı','pages.pendingSubtitle':'Basqa mákemeden jiberilgen nawqaslar','pages.routeSubtitle':'Nawqastıń mákemeler arasındaǵı háreketi hám marshrut sapası','pages.extendedSubtitle':'Wálayat hám mákeme kesiminde tolıq analiz — keste, marshrut, kaskad',
  'feedback.problem':'Mashqala','feedback.suggestion':'Usınıs','feedback.question':'Soraw','feedback.message':'Xabar','feedback.waiting':'Kútilmekte...','feedback.reply':'Juwap keldi','feedback.myMessages':'Meniń xabarlarım','feedback.sendSuccess':'Xabarıńız tabıslı jiberildi!','feedback.placeholder':'Mashqala yamasa usınısıńızdı tolıq jazıń...','feedback.required':'Xabar tekstin kirgiziń','feedback.sendError':'Xabardı jiberip bolmadı. Qayta urınıp kóriń.'
});

// Preserve clinical abbreviations and complete locale parity using explicit UZ fallback values.
for (const locale of ['ru','en','kk']) {
  for (const [key, value] of Object.entries(I18N_CATALOG.uz)) {
    if (!(key in I18N_CATALOG[locale])) I18N_CATALOG[locale][key] = value;
  }
}

// Make every canonical glossary term addressable through the same semantic catalog.
for (const locale of ['uz','ru','en','kk']) {
  for (const [term, values] of Object.entries(window.MEDICAL_GLOSSARY || {})) {
    I18N_CATALOG[locale][`glossary.${term}`] = values[locale];
  }
}

Object.assign(I18N_CATALOG.uz, {
  'dashboard.dataNotLoaded':'Ma’lumot yuklanmagan, biroz kuting',
  'dashboard.exportStarted':'Excel eksport boshlandi'
});
Object.assign(I18N_CATALOG.ru, {
  'dashboard.dataNotLoaded':'Данные ещё не загружены, немного подождите',
  'dashboard.exportStarted':'Экспорт в Excel начат'
});
Object.assign(I18N_CATALOG.en, {
  'dashboard.dataNotLoaded':'Data has not loaded yet. Please wait a moment',
  'dashboard.exportStarted':'Excel export started'
});

const DISPLAY_MONTHS = {
  uz: ['Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyun', 'Iyul', 'Avg', 'Sen', 'Okt', 'Noy', 'Dek'],
  ru: ['янв.', 'фев.', 'мар.', 'апр.', 'мая', 'июн.', 'июл.', 'авг.', 'сен.', 'окт.', 'ноя.', 'дек.'],
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  kk: ['yan.', 'fev.', 'mar.', 'apr.', 'may', 'iyn.', 'iyl.', 'avg.', 'sen.', 'okt.', 'noy.', 'dek.']
};
for (const [language, months] of Object.entries(DISPLAY_MONTHS)) {
  months.forEach((month, index) => { I18N_CATALOG[language][`month.short.${index + 1}`] = month; });
}
Object.assign(I18N_CATALOG.uz, { 'registry.byRegion': 'Viloyatlar kesimida', 'registry.regionFacilities': '{region} muassasalari' });
Object.assign(I18N_CATALOG.ru, { 'registry.byRegion': 'По областям', 'registry.regionFacilities': 'Учреждения: {region}' });
Object.assign(I18N_CATALOG.en, { 'registry.byRegion': 'By region', 'registry.regionFacilities': 'Facilities: {region}' });
Object.assign(I18N_CATALOG.kk, { 'registry.byRegion': 'Wálayatlar boyınsha', 'registry.regionFacilities': '{region} mákemeleri' });

const FACILITY_DISPLAY_NAMES = {
  'facility.name.emergencyCentre': {
    uz: 'Respublika Shoshilinch Tibbiy Yordam Ilmiy Markazi',
    ru: 'Республиканский научный центр экстренной медицинской помощи',
    en: 'Republican Scientific Centre for Emergency Medical Care',
    kk: 'Respublikalıq tez medicinalıq járdem ilimiy orayı'
  },
  'facility.name.cityEmergencyHospital': {
    uz: 'Shahar Tez Tibbiy Yordam Klinik Shifoxonasi',
    ru: 'Городская клиническая больница скорой медицинской помощи',
    en: 'City Emergency Medical Care Clinical Hospital',
    kk: 'Qalalıq tez medicinalıq járdem klinikalıq emlewxanası'
  },
  'facility.name.republicHospital': {
    uz: '1-sonli Respublika Klinik Shifoxonasi',
    ru: 'Республиканская клиническая больница № 1',
    en: 'Republican Clinical Hospital No. 1',
    kk: '1-sanlı Respublikalıq klinikalıq emlewxana'
  }
};
for (const [key, names] of Object.entries(FACILITY_DISPLAY_NAMES)) {
  for (const language of Object.keys(names)) I18N_CATALOG[language][key] = names[language];
}
Object.assign(I18N_CATALOG.uz, { 'wizard.patientTransferredTo':'Bemor {facility}ga o‘tkazildi!', 'wizard.otherInstitution':'boshqa muassasa', 'wizard.incomingFromFacility':'{facility}dan kelgan bemorni qabul qilish' });
Object.assign(I18N_CATALOG.ru, { 'wizard.patientTransferredTo':'Пациент переведён в {facility}.', 'wizard.otherInstitution':'другое учреждение', 'wizard.incomingFromFacility':'Приём пациента, направленного из {facility}' });
Object.assign(I18N_CATALOG.en, { 'wizard.patientTransferredTo':'Patient transferred to {facility}.', 'wizard.otherInstitution':'another facility', 'wizard.incomingFromFacility':'Admit patient referred from {facility}' });
Object.assign(I18N_CATALOG.kk, { 'wizard.patientTransferredTo':'Nawqas {facility} mákemesine ótkerildi.', 'wizard.otherInstitution':'basqa mákeme', 'wizard.incomingFromFacility':'{facility} mákemesinen jiberilgen nawqastı qabıllaw' });
Object.assign(I18N_CATALOG.uz, { 'card.deviceUnavailableAtFacility':'muassasasida {device} apparati yo‘q — bu muolajani shu yerda bajarib bo‘lmaydi.', 'card.transferDestinationQuestion':'Bemor qaysi muassasaga yuboriladi?', 'card.selectCapableFacility':'Bemorni imkoniyati bor muassasaga yo‘naltiring (pastdagi ro‘yxatdan tanlang).' });
Object.assign(I18N_CATALOG.ru, { 'card.deviceUnavailableAtFacility':'нет оборудования для {device} — провести здесь эту процедуру невозможно.', 'card.transferDestinationQuestion':'В какое учреждение направить пациента?', 'card.selectCapableFacility':'Направьте пациента в учреждение с необходимыми возможностями (выберите из списка ниже).' });
Object.assign(I18N_CATALOG.en, { 'card.deviceUnavailableAtFacility':'does not have equipment for {device}; this procedure cannot be performed here.', 'card.transferDestinationQuestion':'Which facility should the patient be sent to?', 'card.selectCapableFacility':'Send the patient to a capable facility (select one from the list below).' });
Object.assign(I18N_CATALOG.kk, { 'card.deviceUnavailableAtFacility':'mákemesinde {device} úskenesi joq — bul emlewdi usı jerde orınlaw múmkin emes.', 'card.transferDestinationQuestion':'Nawqas qaysı mákemege jiberiledi?', 'card.selectCapableFacility':'Nawqastı múmkinshiligi bar mákemege jiberiń (tómendegi dizimnen tańlań).' });
Object.assign(I18N_CATALOG.kk, {
  'dashboard.dataNotLoaded':'Maǵlıwmat ele júklenbedi, biraz kútiń',
  'dashboard.exportStarted':'Excel eksport baslandı'
});
